//! throw new Error("error message")

try {
    console.log("Start try block");
    lalala;
} catch (err) {
    console.log("Error Message", err);
}